-- BioLinked — calculator saved-compound lists, one row per page slug.
-- Mirrors the nutrition_profiles pattern. Run in the Supabase SQL editor.

create table if not exists public.calc_lists (
  id          bigint generated by default as identity primary key,
  page_slug   text        not null unique,
  data        jsonb       not null default '{}'::jsonb,
  updated_at  timestamptz not null default now(),
  created_at  timestamptz not null default now()
);

create index if not exists calc_lists_page_slug_idx on public.calc_lists (page_slug);

alter table public.calc_lists enable row level security;

-- anon may read, create and update. No delete policy, so deletes are refused.
drop policy if exists calc_lists_anon_select on public.calc_lists;
create policy calc_lists_anon_select on public.calc_lists
  for select to anon using (true);

drop policy if exists calc_lists_anon_insert on public.calc_lists;
create policy calc_lists_anon_insert on public.calc_lists
  for insert to anon with check (true);

drop policy if exists calc_lists_anon_update on public.calc_lists;
create policy calc_lists_anon_update on public.calc_lists
  for update to anon using (true) with check (true);
